# Generated by Django 2.2.1 on 2019-06-04 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schichtplan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schichten',
            name='schicht',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schichtplan',
            name='schicht',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schichtplan.Schichten'),
        ),
    ]
