# Generated by Django 2.2.1 on 2019-06-06 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schichtplan', '0002_auto_20190604_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='schichtplan',
            name='schichtmeister',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
